version: "3.8"
services:
  app:
    build: .
    tty: true
    volumes:
      - ./:/go/src/
    ports:
      - "5000:5000"
    env_file:
      - ./env/app.env
    depends_on:
      - db
  prod:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    image: music-tools-backend
    volumes:
      - ./:/go/src/
    depends_on:
      - db
  db:
    image: arm64v8/mysql
    #platform: linux/x86_64
    volumes:
      - data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./env/db.env

volumes:
  data: