# Github Actionsでのテスト用
version: "3.8"
services:
  app:
    build: ./Dockerfile.actions
    tty: true
    volumes:
      - ./:/go/src/
    ports:
      - "5000:5000"
    env_file:
      - ./env/app.test.env
    depends_on:
      - test_db
  #テスト用のDB
  test_db:
    image: mysql
    #platform: linux/x86_64
    #volumes:
    #  - data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3307"
    environment:
     - MYSQL_ROOT_PASSWORD=test
     - MYSQL_DATABASE=test_db
     - MYSQL_USER=testuser
     - MYSQL_PASSWORD=testpassword
     - MYSQL_TCP_PORT=3307