# ビルド用

#stage1
FROM golang:1.19.2

WORKDIR /go/src/
ADD . /go/src/
RUN go mod tidy
WORKDIR /go/src/backend_manager/
RUN GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o /main

#stage2
FROM --platform=linux/amd64 public.ecr.aws/lambda/provided:al2
COPY --from=0 /main ./main
ENTRYPOINT ["./main"]
