package auth

import (
	"testing"

	"example.com/app/utils"
)

func TestAuthConfigure(t *testing.T) {
	t.Run("test auth.Configure()", func(t *testing.T) {
		utils.PrintStruct(auth)
		for _, key := range auth.JWKS {
			utils.PrintStruct(key)
		}
	})

}
func TestAuthCognito(t *testing.T) {
	validToken := "Bearer eyJraWQiOiIzQmJGbDRXTmZTOE9WWkhpUDR4WWRleWNkUlwvRWFzTkhpZ2hLck9hQVVtVT0iLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiTDJ0U291eEFZRGtzUlVjMWFPU3RWQSIsInN1YiI6IjA3MDQyYWM4LWQwZjEtNzAzMi1hMjEyLTZkZDgyMTU5NGM2ZSIsImNvZ25pdG86Z3JvdXBzIjpbImFwLW5vcnRoZWFzdC0xXzA1eWpDdE5HMV9Hb29nbGUiXSwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuYXAtbm9ydGhlYXN0LTEuYW1hem9uYXdzLmNvbVwvYXAtbm9ydGhlYXN0LTFfMDV5akN0TkcxIiwiY29nbml0bzp1c2VybmFtZSI6Imdvb2dsZV8xMDIzMTEzMjU2NzU3OTQ1NzEwNzUiLCJvcmlnaW5fanRpIjoiZWRjMWUyNDctMDM0NC00YmViLTkzMDktNTE0NGUyYWUxYzZkIiwiYXVkIjoiNGRmZjMxMGpsNWlzZ2FkdTEycXAxM2hsbmwiLCJpZGVudGl0aWVzIjpbeyJ1c2VySWQiOiIxMDIzMTEzMjU2NzU3OTQ1NzEwNzUiLCJwcm92aWRlck5hbWUiOiJHb29nbGUiLCJwcm92aWRlclR5cGUiOiJHb29nbGUiLCJpc3N1ZXIiOm51bGwsInByaW1hcnkiOiJ0cnVlIiwiZGF0ZUNyZWF0ZWQiOiIxNjk1NTI4ODQzMDM3In1dLCJ0b2tlbl91c2UiOiJpZCIsImF1dGhfdGltZSI6MTY5NTY4MTcwOSwiZXhwIjoxNjk1Njg1NDMyLCJpYXQiOjE2OTU2ODUxMzIsImp0aSI6IjE1OTdjOTBlLTY1NjAtNGMyMi04NjVhLTk1YzFmOTU4MmVlYiIsImVtYWlsIjoieXN1enVraTA3MjMzQGdtYWlsLmNvbSJ9.MzxeblDUMgZC3lbJ-YE-WdmZiO6w6xgSf8wAmOHZULjzyIZpFnKp_POR-mg1YVt7aIYV6f24Sqw3bPoEajnqHC-QCypaYTyt5niOYQZyJ2i5GkPBtksgv45OnhLCXJk7y637nwvAfRXwUFHREUvi_sr75fTohBSGXo7HTi8XaOPTAWF_wKsNL_VhHKDTR7M_9rf08fOUOGWBZp-9_T-_K5BjpshKgJWJ4pXQmzA7OWfCzgjzarkglP-iZYn4LcL3pGmqMdb-Ro29S7PbjCbBVYlAQsIK8k-bxs0VBiu5aWVRfh4Plg0GHGHsWB3iPDEWdJepTiNysRKclmv2LjiTig"
	t.Run("AuthCognito", func(t *testing.T) {
		claims, err := auth.AuthCognito(validToken)
		if err != nil {
			t.Error(err)
		}
		utils.PrintStruct(claims)
	})

}
